development:
  adapter: postgresql
  database: samepage2_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: samepage2_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: samepage2_production
  pool: 5
  timeout: 5000
